spring.application.name=gs-vault-config

spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true
spring.config.import=vault://

spring.datasource.url=${database.url:jdbc:h2:mem:testdb}
spring.datasource.username=${database.username:sa}
spring.datasource.password=${database.password:}
spring.datasource.driver-class-name=${database.driver:org.h2.Driver}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true